---
- name: Deploy Calculator Docker Image
  hosts: localhost
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: purnendu_17/calculator
        source: pull

    - name: Start Docker Container
      docker_container:
        name: scientific-calculator
        image: purnendu_17/calculator:latest
        state: started
        ports:
          - "8081:8080"